BullTerrier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BullTerrierWeb.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accountsA/', include('allauth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

BullTerrierWeb/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import carrito, comentario, home, pedidos, productocompra, buscarProducto, productosgato, productoshamster, productosperro, registro, suscribirse, addProducto, listaProducto, comentariosLista, editarProducto, removeProducto, register, politicaDePrivacidad, detalle_suscritos, suscritos, lista_suscritos, agregarAlCarrito, carritoComprado, ProductoViewSet, CategoriaViewSet, SuscritosViewSet
from .viewlogin import login_user
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewSet)
router.register('categoria', CategoriaViewSet)
# router.register('suscritos', SuscritosViewSet)

urlpatterns = [
    #Index
    path('', home, name="index"),
    #Carrito
    path('carrito/', carrito, name="carrito"),
    #Carrito Comprado
    path('carrito/comprado/<id>/', carritoComprado, name="carritoComprado"),
    #Comentario
    path('comentario/', comentario, name="comentario"),
    #Comentarios tabla
    path('comentariosLista/', comentariosLista, name="comentariosLista"),
    #Pedidos
    path('pedidos/', pedidos, name="pedidos"),
    #Producto Compra
    path('productos/producto/<id>/', productocompra, name="productocompra"),
    #Producto busqueda
    path('productos/', buscarProducto, name="buscarProducto"),
    #Productos gato
    path('productos/gato/', productosgato, name="productosgato"),
    #Productos Hamster
    path('productos/hamster/', productoshamster, name="productoshamster"),
    #Productos Perro
    path('productos/perro/', productosperro, name="productosperro"),
    #Registro
    path('registro/', registro, name="registro"),
    #Suscribirse
    path('suscribirse/', suscribirse, name="suscribirse"),
    #Añadir producto
    path('productos/add/', addProducto, name="addProducto"),
    #Listar productos
    path('productos/lista/', listaProducto, name="listaProducto"),
    #Editar producto
    path('productos/editar/<id>/', editarProducto, name="editarProducto"),
    #Eliminar producto
    path('productos/remove/<id>/', removeProducto, name="removeProducto"),
    path('productos/addCarrito/<id>/', agregarAlCarrito, name="agregarAlCarrito"),
    #Registrar usuario
    path('register/', register, name="register"),
    path('politica-de-privacidad/', politicaDePrivacidad, name="politicaDePrivacidad"),
    #-API-
    path('api/', include(router.urls)),
    path('login_user/', login_user, name='login_user'),
    path('suscritos/', suscritos, name='suscritos'),
    path('suscritos/lista', lista_suscritos, name='lista_suscritos'),
    path('detalle_suscritos/<id>', detalle_suscritos, name='detalle_suscritos'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djallauth/djallauth/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

BullTerrierWeb/models.py
from distutils.command.upload import upload
from django.db import models
import datetime
import os
from django.contrib.auth.models import User
# Create your models here.

class Usuario(models.Model):
    idUsu = models.IntegerField(primary_key=True, verbose_name="Id Usuario")
    nombreUsu = models.CharField(max_length=50, verbose_name="Nombre de Usuario")
    emailUsu = models.CharField(max_length=50, verbose_name="Email")

    def __str__(self):
        return self.nombreUsu
    
class Categoria(models.Model):
    idCat = models.IntegerField(primary_key=True, verbose_name="Id Categoria")
    nomCat = models.CharField(max_length=30, verbose_name="Nombre Categoria")

    def __str__(self):
        return self.nomCat

def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('uploads/', filename)

class Producto(models.Model):
    idPro = models.IntegerField(primary_key=True, verbose_name="Id Producto") 
    nombrePro = models.CharField(max_length=100, verbose_name="Nombre Producto")
    precioPro = models.IntegerField(verbose_name="Precio Producto")
    descripPro = models.CharField(max_length=500, default="" ,verbose_name="Descripción")
    cantidadPro = models.IntegerField(verbose_name="Cantidad", default=1)
    idCat = models.ForeignKey(Categoria, on_delete=models.CASCADE, default="0", verbose_name="Categoría")
    imgPro = models.ImageField(upload_to="productos", null=True, blank=True, verbose_name="Imagen")
    mostrarPro = models.BooleanField(default='True')
    
    def __str__(self):
        return self.nombrePro

class Carrito(models.Model):
    idCarrito = models.AutoField(primary_key=True, verbose_name="Id")
    cantidad = models.IntegerField(verbose_name="Cantidad", default=1)
    idPro = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Id Producto", default="0")
    usuario = models.IntegerField(verbose_name="Nombre de Usuario", default=0)

class Compra(models.Model):
    idCom = models.IntegerField(primary_key=True, verbose_name="Id Compra")
    fechaCom = models.DateField(verbose_name="Fecha Compra")
    descCom = models.CharField(max_length=1000, verbose_name="Descripción compra", default="")
    idPro = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Id Producto", default="0")
    idUsu = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name="Id Usuario", default="0")

    def __str__(self):
        return self.descCom

class Pedido(models.Model):
    idPed = models.IntegerField(primary_key=True, verbose_name="Id Pedido")
    descPed = models.CharField(max_length=1000, verbose_name="Descripción pedido", default="")
    idPro = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Id Producto", default="0")
    idUsu = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name="Id Usuario", default="0")

    def __str__(self):
        return self.descPed

class Comentario(models.Model):
    idComent = models.AutoField(primary_key=True, verbose_name="Id")
    nombre = models.CharField(max_length=50, verbose_name="Nombre")
    apellido = models.CharField(max_length=50, verbose_name="Apellido")
    correo = models.CharField(max_length=100, verbose_name="Correo electronico")
    calificacion = models.IntegerField(verbose_name="Calificación", default="0")
    comentario = models.CharField(max_length=500, null=True, verbose_name="Comentario")
    def __str__(self):
        return self.correo
    
class Suscripcion(models.Model):
    usu = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, verbose_name="Usuario")
    donacion = models.IntegerField(verbose_name="Donación", default=0)
    suscrito = models.BooleanField(default='True')
    
    def __str__(self):
        return self.usu.username

BullTerrierWeb/views.py
from multiprocessing.spawn import import_main_path
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ComentarioForm, AddProductoForm, CustomUserCreationForm, SuscribirseForm, CarritoForm
from .models import Comentario, Categoria, Producto, Suscripcion, Carrito
from django.contrib import messages
from os import remove
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.db.models import Q
from rest_framework import viewsets, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from rest_framework.authtoken.models import Token
from .serializers import ProductoSerializer, CategoriaSerializer, SuscripcionSerializer
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

class ProductoViewSet(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer
    
class CategoriaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer
    
class SuscritosViewSet(viewsets.ModelViewSet):
    queryset = Suscripcion.objects.all()
    serializer_class = SuscripcionSerializer

# Vista Carrito
def carrito(request):
    usuario = request.user
    suscrito = False
    if usuario.is_authenticated:
        try:
            usuarioSuscrito = get_object_or_404(Suscripcion, usu=usuario)
            suscrito = False
            if usuarioSuscrito.suscrito:
                suscrito = True
            else:
                suscrito = False
        except:
            suscrito = False
    if usuario.is_authenticated:
        vacio = True
        try:
            comprasProductos = Carrito.objects.filter(usuario=usuario.id)
            if len(comprasProductos)!=0:
                vacio = False
                data = {
                    'vacio':vacio,
                    'productos':comprasProductos,
                    'idUsuario':usuario.id,
                    'suscrito':suscrito
                }
            else:
                vacio = True
                data = {
                    'vacio':vacio,
                    'suscrito':suscrito
                }
        except:
            data = {
                'vacio':vacio,
                'suscrito':suscrito
            }
    else:
        data = {
            'vacio': True,
            'suscrito':suscrito
        }
    return render(request, 'BullTerrierWeb/carrito.html', data)

def carritoComprado(request, id):
    productos = Carrito.objects.filter(usuario=id)
    for prod in productos:
        prod.delete()
    messages.success(request, "Comprado correctamente, muchas gracias por confiar en nosotros.")
    return redirect(to="carrito")

# Vista Comentario
def comentario(request):
    datos = {
        'form': ComentarioForm()
    }
    
    if request.method=='POST':
        formulario = ComentarioForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Comentario enviado correctamente")
            return redirect(to="index")
    return render(request, 'BullTerrierWeb/comentario.html', datos)

# Vista Index
def home(request):
    return render(request, 'BullTerrierWeb/index.html')

# Vista Pedidos
def pedidos(request):
    return render(request, 'BullTerrierWeb/pedidos.html')

# Vista Producto Compra
@login_required
def productocompra(request, id):
    usuario = request.user
    producto = get_object_or_404(Producto, idPro=id)
    
    data = {
        'prod':producto
    }
    
    if request.method=='POST':
        carritoNuevo = CarritoForm(request.POST)
        print(carritoNuevo)
        if carritoNuevo.is_valid():
            carritoNuevo.save()
            messages.success(request, "Agregado correctamente al carrito")
        return redirect(to="index")
    return render(request, 'BullTerrierWeb/producto/productocompra.html', data)

@login_required
def agregarAlCarrito(request, id):
    # producto = get_object_or_404(Producto, idPro=id)
    # productoId = int(producto.idPro)
    # usuario = request.user
    # agregarCarrito = CarritoForm()
    # agregarCarrito.idCarrito = 1
    # agregarCarrito.cantidad = 1
    # agregarCarrito.idPro = productoId
    # agregarCarrito.usuario = usuario.id
    # if agregarCarrito.is_valid():
    #     agregarCarrito.save()
    # agregarCarrito = Carrito.objects.create(idCarrito=1, cantidad=1, idPro=productoId, usuario=usuario.id)
    
    return redirect('/productos/producto/'+id+'/')

# Vista Productos Gato
def productosgato(request):
    productos = Producto.objects.all().filter(idCat=3)
    data = {
        'productos':productos
    }
    return render(request, 'BullTerrierWeb/producto/productosgato.html', data)

# Vista Productos Hamster
def productoshamster(request):
    return render(request, 'BullTerrierWeb/producto/productoshamster.html')

# Vista Productos Perro
def productosperro(request):
    productos = Producto.objects.all().filter(idCat=2)
    data = {
        'productos':productos
    }
    return render(request, 'BullTerrierWeb/producto/productosperro.html', data)

# Vista Registro
def registro(request):
    return render(request, 'BullTerrierWeb/registration/registro.html')

# Vista Suscribirse
def suscribirse(request):
    usuario = request.user
    if usuario.is_authenticated:
        try:
            usuarioSuscrito = get_object_or_404(Suscripcion, usu=usuario)
            suscrito = False
            if usuarioSuscrito.suscrito:
                suscrito = True
                data = {
                    'suscrito':suscrito
                }
            else:
                data = {
                    'suscrito':suscrito
                }
        except:
            data = {
                'noIdentificado':True,
                'suscrito':False
            }
    else:
        data = {
            
        }
    if request.method=='POST':
        suscribirNuevo = SuscribirseForm(data=request.POST, instance=usuarioSuscrito)
        print(suscribirNuevo)
        if suscribirNuevo.is_valid():
            suscribirNuevo.save()
            messages.success(request, "Muchas gracias por tu donacion, disfruta de tus descuentos")
        return redirect(to="index")
    
    return render(request, 'BullTerrierWeb/suscribirse.html', data)

# Base (header y footer)
def base(request):
    return render(request, 'BullTerrierWeb/base.html')

# Busqueda de producto
def buscarProducto(request):
    data={
        'productos':Producto.objects.all()
    }
    queryset = request.GET.get("search")
    print(queryset)
    if queryset:
        productos = Producto.objects.filter(
            Q(nombrePro__icontains = queryset) |
            Q(descripPro__icontains = queryset)
        ).distinct()
        print(productos)
        data={
            'productos':productos
        }
    elif queryset == "":
        productos = Producto.objects.all()
        data={
            'productos':productos
        }
    return render(request, 'BullTerrierWeb/producto/buscar.html', data)

# Vista Añadir producto
@permission_required('BullTerrierWeb.add_producto')
def addProducto(request):
    if Producto.objects.all().count()==0:
        idProducto=1
    else:
        idProducto=Producto.objects.latest("idPro")
        idProducto=idProducto.idPro+1
    datos = {
        'idProducto':idProducto,
        'form': AddProductoForm(),
        'categorias': Categoria.objects.all()
    }
    if request.method == "POST":
        producto = AddProductoForm(request.POST, request.FILES)
        if producto.is_valid():
            producto.idPro = request.POST.get("id_idPro")
            producto.nombrePro = request.POST.get("id_nombrePro")
            producto.precioPro = request.POST.get("id_precioPro")
            producto.descripPro = request.POST.get("id_descripPro")
            producto.cantidadPro = request.POST.get("id_cantidadPro")
            producto.mostrarPro = request.POST.get("id_mostrarPro")
            producto.idCat = request.POST.get("id_idCat")
            producto.imgPro = request.FILES.get("id_imgPro")
        
            producto.save()
            messages.success(request, "Producto agregado correctamente")
            return redirect(to="listaProducto")
    return render(request, 'BullTerrierWeb/producto/addProducto.html', datos)

# Vista Borrar Productos
def listaProducto(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)
    
    try:
        paginator = Paginator(productos, 5)
        productos = paginator.page(page)
    except:
        raise Http404
    
    datos = {
        'entity':productos,
        'paginator':paginator
    }
    return render(request, 'BullTerrierWeb/producto/lista.html', datos)

# Vista Lista Comentarios
def comentariosLista(request):
    comentarios = Comentario.objects.all()
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(comentarios, 5)
        comentarios = paginator.page(page)
    except:
        raise Http404
    
    datos = {
        'entity':comentarios,
        'paginator':paginator
    }
    return render(request, 'BullTerrierWeb/comentariosLista.html', datos)

# Vista Editar Producto
@permission_required('BullTerrierWeb.change_producto')
def editarProducto(request, id):
    
    producto = get_object_or_404(Producto, idPro=id)
    
    data = {
        'form': AddProductoForm(instance=producto),
        'prod':producto,
        'idCate':str(producto.idCat),
        'categorias': Categoria.objects.all()
    }
    
    if request.method == 'POST':
        formulario = AddProductoForm(data=request.POST, instance=producto, files=request.FILES)

BullTerrierWeb/templates/BullTerrierWeb/producto/lista.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'BullTerrierWeb/base.html' %}
    {% block content %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <link href="{% static 'BullTerrierWeb/css/style.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'BullTerrierWeb/js/script.js' %}"></script>
    <title>Lista de productos | Bull Terrier</title>
</head>
<body>
    <main class="main">
        <div class="container-sm">
            <br>
            <div class="container overflow-hidden px-4" id="Informacion">
                <div class="row gx-5">
                    <div class="col-12">
                        <div class="p-3 border bg-light" style="text-align: center;">
                            <h1>Productos</h1>
                            <p>Borra o edita los productos que requieras desde esta p&aacute;gina.</p>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="container">
                {% csrf_token %}
                <div class="mb-3">
                    <br>
                    {% if messages %}
                        {% for m in messages %}
                            <script>
                                Swal.fire({
                                    "title": "Felicitaciones",
                                    "text": "{{m}}",
                                    "icon": "success"
                                })
                            </script>
                        {% endfor %}
                    {% endif %}
                    <script>
                        function eliminarProducto(id) {
                            Swal.fire({
                                "title": "¿Estas seguro?",
                                "text": "Esta acción no se puede deshacer",
                                "icon": "question",
                                "showCancelButton":true,
                                "cancelButtonText": "¡No, Cancelar!",
                                "confirmButtonText": "Si, Eliminar",
                                "reverseButtons":true,
                                "confirmButtonColor": "#dc3545"
                            })
                            .then(function(result) {
                                if(result.isConfirmed) {
                                    window.location.href = "/productos/remove/"+id+"/"
                                }
                            })
                        }
                    </script>
                    <div class="row">
                        <div class="col-8 col-sm-10">
                            <h2>Listado de productos:</h2>
                        </div>
                        {% if perms.BullTerrierWeb.add_producto %}
                        <div class="col-4 col-sm-2">
                            <a class="btn btn-primary" href="{% url 'addProducto' %}">+ Agregar</a>
                        </div>
                        {% endif %}
                        <div>
                            {% include 'BullterrierWeb/paginator.html' %}
                        </div>
                        <hr>
                        <div class="container-sm">
                            <table border=2 class="d-flex table table-striped table-hover table-responsive-sm">
                                <tr>
                                    <td>ID Producto</td>
                                    <td>Categoria</td>
                                    <td>Nombre Producto</td>
                                    <td>Precio</td>
                                    <td>Descripci&oacute;n</td>
                                    <td>Stock</td>
                                    <td>Imagen</td>
                                    {% if perms.BullTerrierWeb.change_producto or perms.BullTerrierWeb.delete_producto %}
                                    <td>Opciones</td>
                                    {% endif %}
                                    <td></td>
                                </tr>
                                {% for prod in entity %}
                                    <tr>
                                        <td>{{prod.idPro}}</td>
                                        <td>{{prod.idCat}}</td>
                                        <td>{{prod.nombrePro}}</td>
                                        <td>{{prod.precioPro}}</td>
                                        <td>{{prod.descripPro}}</td>
                                        <td>{{prod.cantidadPro}}</td>
                                        {% if prod.imgPro %}
                                            <td><img src="{{prod.imgPro.url}}" title="{{prod.imgPro.name}}" class="img-producto-sm"></td>
                                        {% else %}
                                            <td><img src="" title="Sin imagen" class="img-producto-sm"></td>
                                        {% endif %}
                                        {% if perms.BullTerrierWeb.change_producto %}
                                        <td><a href="{% url 'editarProducto' prod.idPro %}" class="btn btn-primary">Editar</a></td>
                                        {% endif %}
                                        {% if perms.BullTerrierWeb.delete_producto %}
                                        <td><a href="#" onclick="eliminarProducto({{prod.idPro}})" class="btn btn-danger">Borrar</a></td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% endblock %}
</body>
</html>

BullTerrierWeb/templates/BullTerrierWeb/producto/productocompra.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'BullTerrierWeb/base.html' %}
    {% block content %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'BullTerrierWeb/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'BullTerrierWeb/js/producto.js' %}"></script>
    <title>{{prod.nombrePro}} | Bull Terrier</title>
</head>
<body>
    <main class="main">
        <div class="container-sm">
            <br>
            <br>
            <div class="album py-5 bg-light">
                <div class="container">
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="producto-compra">
                        <div class="col">
                            <div class="card shadow-sm">
                                <a target="_blank" href="{{prod.imgPro.url}}">
                                    <img src='{{prod.imgPro.url}}' alt="{{prod.imgPro.name}}" class="bd-placeholder-img card-img-top" width="100%" height="225" role="img">
                                </a>
                                <div class="card-body">
                                    <h6 class="card-text">{{prod.nombrePro}}</h6>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-8 col-12">
                            <div class="card shadow-sm">
                                <h2 class="card-text" style="margin: 20px;">{{prod.nombrePro}}</h2>
                                <h6 class="" style="margin: 0px 0px 0px 20px;">{{prod.descripPro}}</h6>
                                <h3 style="margin: 20px;">${{prod.precioPro}} CLP</h3>
                                <form enctype="multipart/form-data" method="post">
                                    {% csrf_token %}
                                    {% comment %} <button class="btn-outline-primary" style="margin: 20px;" disabled>COMPRAR</button> {% endcomment %}
                                    <input type="number" name="cantidad" id="id_cantidad" style="display: none;" value="1">
                                    <input type="text" name="idPro" id="id_idPro" style="display: none;" value="{{prod.idPro}}">
                                    <input type="number" name="usuario" id="id_usuario" style="display: none;" value="{{user.id}}">
                                    <button type="submit" class="btn btn-outline-secondary" style="margin: 20px;">AÑADIR AL CARRITO</button>
                                </form>
                                <br>
                            </div>
                        </div>
                    </div>
                    <div class="loading-screen">
                        <h1 id="loading">CARGANDO...</h1>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% endblock %}
</body>
</html>

BullTerrierWeb/templates/BullTerrierWeb/producto/productosgato.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'BullTerrierWeb/base.html' %}
    {% block content %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'BullTerrierWeb/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'BullTerrierWeb/js/productos-gato.js' %}"></script>
    <title>Bull Terrier - Gatos</title>
</head>
<body>
    <main class="main" style="background-color: rgba(85, 85, 85, 0.719);">
        <div class="container-sm">
        <br>
            <div class="container overflow-hidden px-4" id="Informacion">
                <div class="row gx-5">
                    <div class="col-12">
                        <div class="p-3 border bg-light" style="text-align: center;">
                            <h1>Productos para tu gato!</h1> <p>Aqui encontrar&aacute;s variedad de productos para tu gato de elecci&oacute;n &uacute;nica.</p>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="loading-screen">
          <h1 id="loading">CARGANDO...</h1>
        </div>
        {% load humanize %}
        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="productos">
                    {% for prod in productos %}
                        <div class="col">
                            <form action="{% url 'productocompra' prod.idPro %}" id="miForm">
                                <div class="card shadow-sm" id="imagen-productos">
                                    <img src='{{prod.imgPro.url}}' alt="logo.png" class="bd-placeholder-img card-img-top" width="100%" height="225" role="img">
                                    <div class="card-body" id="titulo-productos">
                                        <p class="card-text">{{prod.nombrePro}}</p> 
                                        <div class="d-flex justify-content-between align-items-center" id="precio-productos">
                                            <small class="text-muted">${{prod.precioPro}} CLP</small> 
                                            <input type="submit" class="btn btn-primary" id="enviar" value="Ver producto">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
    {% endblock %}
</body>
</html>