BullTerrier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BullTerrierWeb.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accountsA/', include('allauth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

BullTerrierWeb/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import carrito, comentario, home, pedidos, productocompra, buscarProducto, productosgato, productoshamster, productosperro, registro, suscribirse, addProducto, listaProducto, comentariosLista, editarProducto, removeProducto, register, politicaDePrivacidad, detalle_suscritos, suscritos, lista_suscritos, agregarAlCarrito, carritoComprado, ProductoViewSet, CategoriaViewSet, SuscritosViewSet
from .viewlogin import login_user
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewSet)
router.register('categoria', CategoriaViewSet)
# router.register('suscritos', SuscritosViewSet)

urlpatterns = [
    #Index
    path('', home, name="index"),
    #Carrito
    path('carrito/', carrito, name="carrito"),
    #Carrito Comprado
    path('carrito/comprado/<id>/', carritoComprado, name="carritoComprado"),
    #Comentario
    path('comentario/', comentario, name="comentario"),
    #Comentarios tabla
    path('comentariosLista/', comentariosLista, name="comentariosLista"),
    #Pedidos
    path('pedidos/', pedidos, name="pedidos"),
    #Producto Compra
    path('productos/producto/<id>/', productocompra, name="productocompra"),
    #Producto busqueda
    path('productos/', buscarProducto, name="buscarProducto"),
    #Productos gato
    path('productos/gato/', productosgato, name="productosgato"),
    #Productos Hamster
    path('productos/hamster/', productoshamster, name="productoshamster"),
    #Productos Perro
    path('productos/perro/', productosperro, name="productosperro"),
    #Registro
    path('registro/', registro, name="registro"),
    #Suscribirse
    path('suscribirse/', suscribirse, name="suscribirse"),
    #Añadir producto
    path('productos/add/', addProducto, name="addProducto"),
    #Listar productos
    path('productos/lista/', listaProducto, name="listaProducto"),
    #Editar producto
    path('productos/editar/<id>/', editarProducto, name="editarProducto"),
    #Eliminar producto
    path('productos/remove/<id>/', removeProducto, name="removeProducto"),
    path('productos/addCarrito/<id>/', agregarAlCarrito, name="agregarAlCarrito"),
    #Registrar usuario
    path('register/', register, name="register"),
    path('politica-de-privacidad/', politicaDePrivacidad, name="politicaDePrivacidad"),
    #-API-
    path('api/', include(router.urls)),
    path('login_user/', login_user, name='login_user'),
    path('suscritos/', suscritos, name='suscritos'),
    path('suscritos/lista', lista_suscritos, name='lista_suscritos'),
    path('detalle_suscritos/<id>', detalle_suscritos, name='detalle_suscritos'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djallauth/djallauth/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

BullTerrierWeb/models.py
from distutils.command.upload import upload
from django.db import models
import datetime
import os
from django.contrib.auth.models import User
# Create your models here.

class Usuario(models.Model):
    idUsu = models.IntegerField(primary_key=True, verbose_name="Id Usuario")
    nombreUsu = models.CharField(max_length=50, verbose_name="Nombre de Usuario")
    emailUsu = models.CharField(max_length=50, verbose_name="Email")

    def __str__(self):
        return self.nombreUsu
    
class Categoria(models.Model):
    idCat = models.IntegerField(primary_key=True, verbose_name="Id Categoria")
    nomCat = models.CharField(max_length=30, verbose_name="Nombre Categoria")

    def __str__(self):
        return self.nomCat

def filepath(request, filename):
    old_filename = filename
    timeNow = datetime.datetime.now().strftime('%Y%m%d%H:%M:%S')
    filename = "%s%s" % (timeNow, old_filename)
    return os.path.join('uploads/', filename)

class Producto(models.Model):
    idPro = models.IntegerField(primary_key=True, verbose_name="Id Producto") 
    nombrePro = models.CharField(max_length=100, verbose_name="Nombre Producto")
    precioPro = models.IntegerField(verbose_name="Precio Producto")
    descripPro = models.CharField(max_length=500, default="" ,verbose_name="Descripción")
    cantidadPro = models.IntegerField(verbose_name="Cantidad", default=1)
    idCat = models.ForeignKey(Categoria, on_delete=models.CASCADE, default="0", verbose_name="Categoría")
    imgPro = models.ImageField(upload_to="productos", null=True, blank=True, verbose_name="Imagen")
    mostrarPro = models.BooleanField(default='True')
    
    def __str__(self):
        return self.nombrePro

class Carrito(models.Model):
    idCarrito = models.AutoField(primary_key=True, verbose_name="Id")
    cantidad = models.IntegerField(verbose_name="Cantidad", default=1)
    idPro = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Id Producto", default="0")
    usuario = models.IntegerField(verbose_name="Nombre de Usuario", default=0)

class Compra(models.Model):
    idCom = models.IntegerField(primary_key=True, verbose_name="Id Compra")
    fechaCom = models.DateField(verbose_name="Fecha Compra")
    descCom = models.CharField(max_length=1000, verbose_name="Descripción compra", default="")
    idPro = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Id Producto", default="0")
    idUsu = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name="Id Usuario", default="0")

    def __str__(self):
        return self.descCom

class Pedido(models.Model):
    idPed = models.IntegerField(primary_key=True, verbose_name="Id Pedido")
    descPed = models.CharField(max_length=1000, verbose_name="Descripción pedido", default="")
    idPro = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name="Id Producto", default="0")
    idUsu = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name="Id Usuario", default="0")

    def __str__(self):
        return self.descPed

class Comentario(models.Model):
    idComent = models.AutoField(primary_key=True, verbose_name="Id")
    nombre = models.CharField(max_length=50, verbose_name="Nombre")
    apellido = models.CharField(max_length=50, verbose_name="Apellido")
    correo = models.CharField(max_length=100, verbose_name="Correo electronico")
    calificacion = models.IntegerField(verbose_name="Calificación", default="0")
    comentario = models.CharField(max_length=500, null=True, verbose_name="Comentario")
    def __str__(self):
        return self.correo
    
class Suscripcion(models.Model):
    usu = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, verbose_name="Usuario")
    donacion = models.IntegerField(verbose_name="Donación", default=0)
    suscrito = models.BooleanField(default='True')
    
    def __str__(self):
        return self.usu.username

BullTerrierWeb/views.py
from multiprocessing.spawn import import_main_path
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ComentarioForm, AddProductoForm, CustomUserCreationForm, SuscribirseForm, CarritoForm
from .models import Comentario, Categoria, Producto, Suscripcion, Carrito
from django.contrib import messages
from os import remove
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.db.models import Q
from rest_framework import viewsets, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from rest_framework.authtoken.models import Token
from .serializers import ProductoSerializer, CategoriaSerializer, SuscripcionSerializer
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

class ProductoViewSet(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer
    
class CategoriaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer
    
class SuscritosViewSet(viewsets.ModelViewSet):
    queryset = Suscripcion.objects.all()
    serializer_class = SuscripcionSerializer

# Vista Carrito
def carrito(request):
    usuario = request.user
    suscrito = False
    if usuario.is_authenticated:
        try:
            usuarioSuscrito = get_object_or_404(Suscripcion, usu=usuario)
            suscrito = False
            if usuarioSuscrito.suscrito:
                suscrito = True
            else:
                suscrito = False
        except:
            suscrito = False
    if usuario.is_authenticated:
        vacio = True
        try:
            comprasProductos = Carrito.objects.filter(usuario=usuario.id)
            if len(comprasProductos)!=0:
                vacio = False
                data = {
                    'vacio':vacio,
                    'productos':comprasProductos,
                    'idUsuario':usuario.id,
                    'suscrito':suscrito
                }
            else:
                vacio = True
                data = {
                    'vacio':vacio,
                    'suscrito':suscrito
                }
        except:
            data = {
                'vacio':vacio,
                'suscrito':suscrito
            }
    else:
        data = {
            'vacio': True,
            'suscrito':suscrito
        }
    return render(request, 'BullTerrierWeb/carrito.html', data)

def carritoComprado(request, id):
    productos = Carrito.objects.filter(usuario=id)
    for prod in productos:
        prod.delete()
    messages.success(request, "Comprado correctamente, muchas gracias por confiar en nosotros.")
    return redirect(to="carrito")

# Vista Comentario
def comentario(request):
    datos = {
        'form': ComentarioForm()
    }
    
    if request.method=='POST':
        formulario = ComentarioForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Comentario enviado correctamente")
            return redirect(to="index")
    return render(request, 'BullTerrierWeb/comentario.html', datos)

# Vista Index
def home(request):
    return render(request, 'BullTerrierWeb/index.html')

# Vista Pedidos
def pedidos(request):
    return render(request, 'BullTerrierWeb/pedidos.html')

# Vista Producto Compra
@login_required
def productocompra(request, id):
    usuario = request.user
    producto = get_object_or_404(Producto, idPro=id)
    
    data = {
        'prod':producto
    }
    
    if request.method=='POST':
        carritoNuevo = CarritoForm(request.POST)
        print(carritoNuevo)
        if carritoNuevo.is_valid():
            carritoNuevo.save()
            messages.success(request, "Agregado correctamente al carrito")
        return redirect(to="index")
    return render(request, 'BullTerrierWeb/producto/productocompra.html', data)

@login_required
def agregarAlCarrito(request, id):
    # producto = get_object_or_404(Producto, idPro=id)
    # productoId = int(producto.idPro)
    # usuario = request.user
    # agregarCarrito = CarritoForm()
    # agregarCarrito.idCarrito = 1
    # agregarCarrito.cantidad = 1
    # agregarCarrito.idPro = productoId
    # agregarCarrito.usuario = usuario.id
    # if agregarCarrito.is_valid():
    #     agregarCarrito.save()
    # agregarCarrito = Carrito.objects.create(idCarrito=1, cantidad=1, idPro=productoId, usuario=usuario.id)
    
    return redirect('/productos/producto/'+id+'/')

# Vista Productos Gato
def productosgato(request):
    productos = Producto.objects.all().filter(idCat=3)
    data = {
        'productos':productos
    }
    return render(request, 'BullTerrierWeb/producto/productosgato.html', data)

# Vista Productos Hamster
def productoshamster(request):
    return render(request, 'BullTerrierWeb/producto/productoshamster.html')

# Vista Productos Perro
def productosperro(request):
    productos = Producto.objects.all().filter(idCat=2)
    data = {
        'productos':productos
    }
    return render(request, 'BullTerrierWeb/producto/productosperro.html', data)

# Vista Registro
def registro(request):
    return render(request, 'BullTerrierWeb/registration/registro.html')

# Vista Suscribirse
def suscribirse(request):
    usuario = request.user
    if usuario.is_authenticated:
        try:
            usuarioSuscrito = get_object_or_404(Suscripcion, usu=usuario)
            suscrito = False
            if usuarioSuscrito.suscrito:
                suscrito = True
                data = {
                    'suscrito':suscrito
                }
            else:
                data = {
                    'suscrito':suscrito
                }
        except:
            data = {
                'noIdentificado':True,
                'suscrito':False
            }
    else:
        data = {
            
        }
    if request.method=='POST':
        suscribirNuevo = SuscribirseForm(data=request.POST, instance=usuarioSuscrito)
        print(suscribirNuevo)
        if suscribirNuevo.is_valid():
            suscribirNuevo.save()
            messages.success(request, "Muchas gracias por tu donacion, disfruta de tus descuentos")
        return redirect(to="index")
    
    return render(request, 'BullTerrierWeb/suscribirse.html', data)

# Base (header y footer)
def base(request):
    return render(request, 'BullTerrierWeb/base.html')

# Busqueda de producto
def buscarProducto(request):
    data={
        'productos':Producto.objects.all()
    }
    queryset = request.GET.get("search")
    print(queryset)
    if queryset:
        productos = Producto.objects.filter(
            Q(nombrePro__icontains = queryset) |
            Q(descripPro__icontains = queryset)
        ).distinct()
        print(productos)
        data={
            'productos':productos
        }
    elif queryset == "":
        productos = Producto.objects.all()
        data={
            'productos':productos
        }
    return render(request, 'BullTerrierWeb/producto/buscar.html', data)

# Vista Añadir producto
@permission_required('BullTerrierWeb.add_producto')
def addProducto(request):
    if Producto.objects.all().count()==0:
        idProducto=1
    else:
        idProducto=Producto.objects.latest("idPro")
        idProducto=idProducto.idPro+1
    datos = {
        'idProducto':idProducto,
        'form': AddProductoForm(),
        'categorias': Categoria.objects.all()
    }
    if request.method == "POST":
        producto = AddProductoForm(request.POST, request.FILES)
        if producto.is_valid():
            producto.idPro = request.POST.get("id_idPro")
            producto.nombrePro = request.POST.get("id_nombrePro")
            producto.precioPro = request.POST.get("id_precioPro")
            producto.descripPro = request.POST.get("id_descripPro")
            producto.cantidadPro = request.POST.get("id_cantidadPro")
            producto.mostrarPro = request.POST.get("id_mostrarPro")
            producto.idCat = request.POST.get("id_idCat")
            producto.imgPro = request.FILES.get("id_imgPro")
        
            producto.save()
            messages.success(request, "Producto agregado correctamente")
            return redirect(to="listaProducto")
    return render(request, 'BullTerrierWeb/producto/addProducto.html', datos)

# Vista Borrar Productos
def listaProducto(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)
    
    try:
        paginator = Paginator(productos, 5)
        productos = paginator.page(page)
    except:
        raise Http404
    
    datos = {
        'entity':productos,
        'paginator':paginator
    }
    return render(request, 'BullTerrierWeb/producto/lista.html', datos)

# Vista Lista Comentarios
def comentariosLista(request):
    comentarios = Comentario.objects.all()
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(comentarios, 5)
        comentarios = paginator.page(page)
    except:
        raise Http404
    
    datos = {
        'entity':comentarios,
        'paginator':paginator
    }
    return render(request, 'BullTerrierWeb/comentariosLista.html', datos)

# Vista Editar Producto
@permission_required('BullTerrierWeb.change_producto')
def editarProducto(request, id):
    
    producto = get_object_or_404(Producto, idPro=id)
    
    data = {
        'form': AddProductoForm(instance=producto),
        'prod':producto,
        'idCate':str(producto.idCat),
        'categorias': Categoria.objects.all()
    }
    
    if request.method == 'POST':
        formulario = AddProductoForm(data=request.POST, instance=producto, files=request.FILES)

BullTerrierWeb/templates/BullTerrierWeb/comentario.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'BullTerrierWeb/base.html' %}
    {% block content %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <link href="{% static 'BullTerrierWeb/css/style.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'BullTerrierWeb/js/script.js' %}"></script>
    <title>Dejanos tu opinion | Bull Terrier</title>
</head>

<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <main>
        <div class="container">
            <form enctype="multipart/form-data" method="post" name="formulario" id="formulario">
                {% csrf_token %}
                <div class="mb-3">
                    <div class="row">
                        <div class="col">
                            <label for="id_nombre" class="form-label">Nombre (Obligatorio)</label>
                            <input type="text" class="form-control" name="nombre" maxlength="50" id="id_nombre" placeholder="Ingrese su Nombre" required>
                        </div>
                        <div class="col">
                            <label for="id_apellido" class="form-label">Apellido (Obligatorio)</label>
                            <input type="text" class="form-control" name="apellido" maxlength="50" id="id_apellido" placeholder="Ingrese su Apellido" required>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <label for="id_correo" class="form-label">Direcci&oacute;n de Correo (Obligatorio)</label>
                    <input type="email" class="form-control" name="correo" maxlength="100" id="id_correo" placeholder="Ingrese su Correo" required>
                </div>
                <br>
                <label for="id_calificacion">Calificanos (Obligatorio)</label>
                <div class="mb-3 form-floating">
                    <select class="form-select" name="calificacion" id="id_calificacion" onblur="pierdeFoco()" required>
                      <option selected value="0">Seleccione su calificacfion</option>
                      <option value="1">Excelente</option>
                      <option value="2">Buena</option>
                      <option value="3">Regular</option>
                      <option value="4">Mala</option>
                      <option value="5">Pesima</option>
                    </select>
                </div>
                <div class="mb-3">
                    <div class="row">
                        <label for="id_comentario">Escribenos tu comentario (Opcional)</label>
                        <div class="mb-3 form-floating">
                            <input type="text" class="form-control" name="comentario" maxlength="500" id="id_comentario" placeholder="Comentario" required>
                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary" id="enviar" value="Enviar">Enviar</button>
                        </div>
                        <div id="error" class="alert alert-danger" role="alert"></div>
            </form>
            </div>
    </main>
    {% endblock %}
</body>

</html>

BullTerrierWeb/templates/BullTerrierWeb/envio.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
   <head>
      {% load static %}
      <meta charset="utf-8">
      <title>Solicitud de envio</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'BullTerrierWeb/css/styleEnvio.css' %}">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
   <body>
      <div class="wrapper">
         <div class="title-text">
            <div class="title login" id="envio">
               {{envio}}
            </div>
         </div>
      </div>
      <a href="{% url 'index' %}"><button class="btn btn-light">Inicio</button></a>
   </body>
</html>

BullTerrierWeb/templates/BullTerrierWeb/suscribirse.html
<!DOCTYPE html>
<html lang="en">
    {% extends 'BullTerrierWeb/base.html' %}
    {% block content %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'BullTerrierWeb/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'BullTerrierWeb/js/script.js' %}"></script>
    <title>Suscribete | Bull Terrier</title>
</head>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <main>
        <div class="container">
            {% if user.is_authenticated and not suscrito and not noIdentificado %}
            <form enctype="multipart/form-data" method="post" name="SuscribirseForm" id="SuscribirseForm">
                {% csrf_token %}
                <div class="mb-3">
                    <div class="row">
                        <div class="col">
                            <label for="nombre" class="form-label">Nombre de Usuario</label>
                            <input type="text" class="form-control" value="{{user.username}}" readonly>
                            <input type="text" class="form-control" id="id_usu" name="usu" value="{{user.id}}" style="display: none;">
                        </div>
                        {% comment %} <div class="col">
                            <label for="apellido" class="form-label">Apellido</label>
                            <input type="text" class="form-control" name="apellido" value="" readonly>
                        </div> {% endcomment %}
                    </div>
                </div>
                {% comment %} <div class="col">
                    <label for="correo" class="form-label">Direcci&oacute;n de Correo</label>
                    <input type="email" class="form-control" id="correo" name="correo" value="{{user.mail}}" readonly>
                </div> {% endcomment %}
                <hr>
                <label for="donacion">Donaci&oacute;n (Obligatorio)</label>
                <div class="mb-3 form-floating">
                    <select name="donacion" id="id_donacion" class="form-select" onselect="pierdeFoco()" required>
                    <option value="0" selected>Selecciona alguna opci&oacute;n</option>
                        <option value="1000">$1.000</option>
                        <option value="2000">$2.000</option>
                        <option value="3000">$3.000</option>
                        <option value="4000">$4.000</option>
                        <option value="5000">$5.000</option>
                </select>
                <input type="checkbox" name="suscrito" id="id_suscrito" style="display: none;" checked>
                <hr>
                <div class="card text-center text-white bg-secondary mb-3">
                    <div class="card-body">
                    <p>Al suscribirte no importa el monto de donaci&oacute;n... Esto significa que por el minimo puedes conseguir los mismos beneficios, cada uno elige la donaci&oacute;n que quiera dejar.</p><p>(No puedes suscribirte mas de una vez)</p>
                    </div>
                </div>
                </div>
                {% comment %} <label for="miCom">Escribenos tu comentario (Opcional)</label>
                <div class="mb-3">
                    <div class="row">
                        <div class="mb-3 form-floating">
                            <textarea class="form-control" name="miCom" id="miDor" cols="50" rows="30" placeholder="comentario"></textarea>
                        </div> {% endcomment %}
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary" id="enviar" value="Enviar">Enviar</button>
                        </div>
                        <div id="error" class="alert alert-danger" role="alert"></div>
            </form>
            {% elif user.is_authenticated and suscrito and not noIdentificado %}
            <div class="p-3 border bg-light">
                <div class="d-flex justify-content-center">
                    <h2>¡Ya estas suscrito, disfruta de tus descuentos!</h2>
                </div>
                <br>
                <div class="row justify-content-md-center">
                    <div class="col col-md-auto">
                        <a href="{% url 'productosgato' %}" class="btn btn-primary">Productos Gato</a>
                    </div>
                    <div class="col-md-auto">
                        <a href="{% url 'index' %}" class="btn btn-secondary">Inicio</a>
                    </div>
                    <div class="col col-md-auto">
                        <a href="{% url 'productosperro' %}" class="btn btn-primary">Productos Perro</a>
                    </div>
                </div>
                <br>
            </div>
            <br>
            {% elif user.is_authenticated and noIdentificado %}
            <br>
            <div class="p-3 border bg-light">
                <div class="d-flex justify-content-center">
                    <h2>Hubo un error, por favor intenta mas tarde.</h2>
                </div>
                <hr>
                <div class="d-flex justify-content-center">
                    <p>O intenta comunicarte con servicio al cliente <b>ayuda@bullterrier.cl</b> .</p>
                </div>
            </div>
            <br>
            {% elif not user.is_authenticated %}
            <div class="p-3 border bg-light">
                <br>
                <div class="d-flex justify-content-center">
                    <h2>Por favor, <a href="{% url 'login' %}" style="color: black;">Inicia sesi&oacute;n</a> o <a href="{% url 'register' %}" style="color: black;">Registrate</a> para suscribirte.</h2>
                </div>
                <br>
            </div>
            {% endif %}
            </div>
    </main>
    {% endblock %}
</body>

</html>